# Generated by Django 2.1.2 on 2018-11-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggworks_api', '0002_auto_20181104_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='photo_path',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile_photo'),
        ),
    ]
