# Generated by Django 2.1.2 on 2018-11-11 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ggworks_api', '0004_author_blog_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
