# Generated by Django 2.1.2 on 2018-11-17 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ggworks_api', '0006_auto_20181113_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='company',
            new_name='email',
        ),
    ]
