# Generated by Django 2.1.2 on 2018-11-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggworks_api', '0008_userprofile_photo_small'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo_small',
            field=models.ImageField(blank=True, upload_to='profile_photo'),
        ),
    ]
