# Generated by Django 2.1.2 on 2018-11-30 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ggworks_api', '0010_auto_20181123_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='chat_room',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='chat_user',
        ),
        migrations.RemoveField(
            model_name='chatroomuser',
            name='chat_room',
        ),
        migrations.RemoveField(
            model_name='chatroomuser',
            name='chat_user',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='ChatRoomUser',
        ),
    ]
